<a href="https://colab.research.google.com/github/Peksyaji/Orbit-AI-Mastery/blob/main/Muzero_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Yang kami ubah dari code asli:
- Pembagian data training dan testing dari 7:3 menjadi 6:4
- Menggunakan paremater standar untuk setiap model
- Menambahkan model XGBoost dan Extra Trees

In [2]:
# Load Data
df = pd.read_csv('https://raw.githubusercontent.com/Peksyaji/Orbit-AI-Mastery/main/datasets/iris_data.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
print(set(df['class']))

{'Iris-virginica', 'Iris-setosa', 'Iris-versicolor'}


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
# Membagi variabel menjadi variabel independen dan dependen
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
# Encoding label
le = LabelEncoder()
y = le.fit_transform(y)

In [7]:
# Splitting dataset menjadi data training sebesar 60% dan data testing sebesar 40%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [8]:
# Random Forest
RF = RandomForestClassifier()
model1 = RF.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)

In [9]:
# Menghitung confusion matrix dari y hasil prediksi dan y nilai asli
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)

[[17  0  0]
 [ 0 21  0]
 [ 0  3 19]]


In [10]:
# Menampilkan nilai akurasi untuk prediksi di data training
print('Training-set accuracy score:', model1.score(X_train, y_train))
# Menampilkan nilai akurasi untuk prediksi di data testing
print('Test-set accuracy score:', model1.score(X_test, y_test))

Training-set accuracy score: 1.0
Test-set accuracy score: 0.95


In [11]:
# Nilai akurasi yang diperoleh dari model Random Forest
print('Random Forest Model Accuracy:',accuracy_score(y_test,y_pred1))

Random Forest Model Accuracy: 0.95


In [12]:
# AdaBoost
AB = AdaBoostClassifier()
model2 = AB.fit(X_train, y_train)
y_pred2 = model2.predict(X_test)

In [13]:
# Menghitung confusion matrix dari y hasil prediksi dan y nilai asli
cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)

[[17  0  0]
 [ 0 20  1]
 [ 0  2 20]]


In [14]:
# Menampilkan nilai akurasi untuk prediksi di data training
print('Training-set accuracy score:', model2.score(X_train, y_train))
# Menampilkan nilai akurasi untuk prediksi di data testing
print('Test-set accuracy score:', model2.score(X_test, y_test))
# Nilai akurasi yang diperoleh dari model Random Forest
print('Random Forest Model Accuracy:',accuracy_score(y_test,y_pred2))

Training-set accuracy score: 0.9888888888888889
Test-set accuracy score: 0.95
Random Forest Model Accuracy: 0.95


In [15]:
# XGBoost
xgb = xgb.XGBClassifier()
model3 = xgb.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)

In [16]:
# Menghitung confusion matrix dari y hasil prediksi dan y nilai asli
cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)

[[17  0  0]
 [ 0 20  1]
 [ 0  2 20]]


In [17]:
# Menampilkan nilai akurasi untuk prediksi di data training
print('Training-set accuracy score:', model3.score(X_train, y_train))
# Menampilkan nilai akurasi untuk prediksi di data testing
print('Test-set accuracy score:', model3.score(X_test, y_test))
# Nilai akurasi yang diperoleh dari model Random Forest
print('Random Forest Model Accuracy:',accuracy_score(y_test,y_pred3))

Training-set accuracy score: 1.0
Test-set accuracy score: 0.95
Random Forest Model Accuracy: 0.95


In [18]:
# Extra-trees
et = ExtraTreesClassifier()
model4 = et.fit(X_train, y_train)
y_pred4 = model4.predict(X_test)

In [19]:
# Menghitung confusion matrix dari y hasil prediksi dan y nilai asli
cm4 = confusion_matrix(y_test, y_pred4)
print(cm4)

[[17  0  0]
 [ 0 20  1]
 [ 0  2 20]]


In [21]:
# Menampilkan nilai akurasi untuk prediksi di data training
print('Training-set accuracy score:', model4.score(X_train, y_train))
# Menampilkan nilai akurasi untuk prediksi di data testing
print('Test-set accuracy score:', model4.score(X_test, y_test))
# Nilai akurasi yang diperoleh dari model Random Forest
print('Random Forest Model Accuracy:',accuracy_score(y_test,y_pred4))

Training-set accuracy score: 1.0
Test-set accuracy score: 0.9333333333333333
Random Forest Model Accuracy: 0.9333333333333333


# Kesimpulan
- Terjadi kenaikan akurasi model baik untuk model Random Forest maupun AdaBoost dari sebelum dilakukan pengubahan code dengan sesudah dilakukan perubahan code
- Model yang kami pilih adalah AdaBoost karena memiliki akurasi yang baik serta tidak mengalami overfitting ataupun underfitting